#This Travis config template file was taken from https://github.com/FriendsOfCake/travis
language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

env:
  matrix:
    - DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
  - php: 7.1
    env: PHPCS=1 DEFAULT=0

  - php: 7.1
    env: COVERAGE=1 DEFAULT=0 DB=mysql db_dsn='mysql://travis@0.0.0.0/cakephp_test'

install:
  - sh -c "if [ '$HHVM' != '1' ]; then phpenv config-rm xdebug.ini; fi"
  - composer self-update
  - composer install --prefer-dist --no-interaction

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;' && mysql -e \"GRANT ALL PRIVILEGES ON cakephp_test.* TO 'travis'@'%';\"; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then composer require cakephp/cakephp-codesniffer:dev-master; fi"

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then vendor/bin/phpunit --stderr; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi"
  - sh -c "if [ '$COVERAGE' = '1' ]; then phpdbg -qrr vendor/bin/phpunit --stderr --coverage-clover coverage.xml; fi"

after_success:
  - sh -c "if [ '$COVERAGE' = '1' ]; then curl -s https://codecov.io/bash | bash; fi"

notifications:
  email: false
